### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by stemy2** [YunoHost-Apps/peertube-search-index_ynh#11]
### Describe the bug

An error occurred inside the app installation script.

### Context

- Hardware: Desktop pc
- YunoHost version: 4.1.6
- I have access to my server: Full
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: no
- Using, or trying to install package version/branch: master

### Steps to reproduce
    ```
    sudo yunohost app install peertube-search-index
    ```
### Expected behavior

App installation.

### Logs

https://paste.yunohost.org/raw/arirekosof

**Comment by stemy2** [comment]
Why did you closed my ticket without answering anything ?

**Comment by yalh76** [comment]
Because it's not a ticket but an issue. And you should first read your own logs before opening an issue.

**Comment by stemy2** [comment]
OK, i reformulate.

Why did you closed my issue without answering anything ?

And yes, i have read the logs, and what i saw didn't help me to know exactly how to fix it.

And since it's an installation issue, i though it would be the right place to report it.
